#!/bin/bash

version=phantomjs-1.7.0-linux-i686-dynamic
wget http://phantomjs.googlecode.com/files/$version.tar.bz2
tar xjf $version.tar.bz2
ln -fs `pwd`/$version/bin/phantomjs /usr/local/bin/phantomjs
